name: Déploiement continu Spring Boot + Angular

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Variables d'environnement
  
       # **JAVA_VERSION: 20
        # Spécifier la version Java pour Spring Boot**

    steps:
      - name: Extraction du code source
        uses: actions/checkout@v3

      - name: Configuration de Java 20
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Installation des dépendances Maven
        run: mvn install -DskipTests

      - name: Génération du build Angular
        run: ng build --prod

      - name: Génération du JAR Spring Boot
        run: mvn package

      - name: Déploiement sur l'ordinateur de l'utilisateur
        run: |
          # Téléchargement du script d'installation/déploiement
        #  curl -OL https://exemple.com/script.sh

          # Exécution du script d'installation/déploiement
          #chmod +x script.sh
         # ./script.sh
